# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbbbbc44fc16318635548baa59f2ace97991e5c23caf8487b3e23e692bf45f3ae737afc58ac3f24cec458f612eba5266fa87741ab3afe53c6cc0f6381b07e1ef

test:
  secret_key_base: 9044fcdea4a60ac19eb6a496bb975d9eace344c1baa960631c0b087c5a09030d5cbab2a93f07277b0a0204d2f6470482ea6fa48e53dfa09f1951f9df5aa87b02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
